# General Settings
site_name: Rest API Description
site_url: https://boschrexroth.github.io/rest-api-description
site_description: foo bar
site_author: Bosch Rexroth AG
copyright: Copyright &copy; 2020-2021 Bosch Rexroth AG

# Repository Settings
repo_name: boschrexroth/rest-api-description
edit_uri: edit/master/doc/
repo_url: https://github.com/boschrexroth/rest-api-description
remote_branch: gh-pages

docs_dir: private/docs
site_dir: public/site
use_directory_urls: false

# Theming and style
theme:
  name: material
  custom_dir: private/docs
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  favicon: assets/favicon.png
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: rexroth-light
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - styles/ctrlx.css

# Plugins
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/boschrexroth
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/boschrexroth

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details

# Content
nav:
    - Home: README.md
    - ctrlX CORE: 
      - Overview: ctrlx-automation/ctrlx-core/README.md
      
      
    - ctrlX WORKS:
      - Overview: ctrlx-automation/ctrlx-works/README.md